ecp_node_deviceId: 10082992
ecp_node_deviceSecret: NzRkZWRiM2IzMWJiNzE5ZjBmMzA=
ecp_productId: 104291
ecp_productSecret: NGMyZTU3ZDgzNjljM2I4YWY0Njk=
draft_property_id: 11326
identifier_name: identifier_fadb4
property_id: 11623
category_id: 28
ecp_deviceId: 10082993
ecp_deviceSecret: Y2UyMzM5ODY4MmJmZWIxMTg5ZDk=
batch_id: 100450
channel_id: 232
group_id: 382
ecp_node_deviceId: 10082996
ecp_node_deviceSecret: NjQ0MGNlOTZiMWIxZGE0OGQ2Njc=
ecp_productId: 104292
ecp_productSecret: MTJhNjBiY2JmZjQ4YjFhNjk4Mjg=
draft_property_id: 11327
identifier_name: identifier_03db1
property_id: 11624
category_id: 28
ecp_deviceId: 10082997
ecp_deviceSecret: Y2VlOTc3NmZmZGJkZTNiZDc0YjI=
batch_id: 100451
channel_id: 233
group_id: 383
destination_id: 14268
edge_router_id: 11435
router_id: 11436
rule_id: 8ae48e9673e145580173e73ed073001b
