ecp_node_deviceId: 10082933
ecp_node_deviceSecret: OGIyM2Q5NjVhODJlODczYjg5OTY=
ecp_productId: 104276
ecp_productSecret: NjMwMWNiOTI0ZDRlNjM1OWY3YWI=
draft_property_id: 11309
identifier_name: identifier_c4021
property_id: 11599
category_id: 28
ecp_deviceId: 10082934
ecp_deviceSecret: ZTQ5M2E3ZmMwZjRmMGM0MDhhOTQ=
batch_id: 100436
channel_id: 218
group_id: 368
destination_id: 14257
edge_router_id: 11413
router_id: 11414
rule_id: 8ae48e9673e145580173e67d320d0005
ecp_node_deviceId: 10082937
ecp_node_deviceSecret: YmI1NTNiZDNiZWQ5MjcyZTYyYTk=
ecp_productId: 104277
ecp_productSecret: YzFkZWNjNzdjYTFlNmJjMjc1ZDI=
draft_property_id: 11310
identifier_name: identifier_4ea2d
property_id: 11600
category_id: 28
ecp_deviceId: 10082938
ecp_deviceSecret: NjJiYmU4YmI0MzY1MDVmNTQzNjg=
batch_id: 100437
channel_id: 219
group_id: 369
destination_id: 14258
edge_router_id: 11415
router_id: 11416
rule_id: 8ae48e9673e145580173e68711bf0007
ecp_node_deviceId: 10082941
ecp_node_deviceSecret: OTJhZDdjNDUxM2NiMmFmZGYyNTM=
ecp_productId: 104278
ecp_productSecret: YWE2MmYxM2NiZGM2OWVlZjY3MzI=
draft_property_id: 11311
identifier_name: identifier_4ec13
property_id: 11601
category_id: 28
ecp_deviceId: 10082942
ecp_deviceSecret: OWYwOWFiNTVlZDVlYjI0NjVjZjk=
batch_id: 100438
channel_id: 220
group_id: 370
destination_id: 14259
edge_router_id: 11417
router_id: 11418
rule_id: 8ae48e9673e145580173e6908b4d0009
ecp_node_deviceId: 10082945
ecp_node_deviceSecret: YjM5Mjg1YTdjOTZhMTRjZTc3OGM=
ecp_productId: 104279
ecp_productSecret: Yjg3MmVjY2QzNmEzOGMyYjJiZDQ=
draft_property_id: 11312
identifier_name: identifier_5b3ac
property_id: 11602
category_id: 28
ecp_deviceId: 10082946
ecp_deviceSecret: ODJhOWNjMDlmMDRkOTAyZjE3NTU=
batch_id: 100439
channel_id: 221
group_id: 371
destination_id: 14260
edge_router_id: 11419
router_id: 11420
rule_id: 8ae48e9673e145580173e6921ae9000b
ecp_node_deviceId: 10082949
ecp_node_deviceSecret: NjgyMzA1YWVjMzVhNjRlNjIyZmM=
ecp_productId: 104280
ecp_productSecret: NjZkM2JjMzk1MjFkNmNlNTczYTY=
draft_property_id: 11313
identifier_name: identifier_f41dc
property_id: 11603
category_id: 28
ecp_deviceId: 10082950
ecp_deviceSecret: MTQxYjdlNjUzNTU2MmMyZWEyNDE=
batch_id: 100440
channel_id: 222
group_id: 372
destination_id: 14261
edge_router_id: 11421
router_id: 11422
rule_id: 8ae48e9673e145580173e697ce15000d
ecp_node_deviceId: 10082953
ecp_node_deviceSecret: NWY1YTBkZGMzZDgxMzI3NDE3ZWU=
ecp_productId: 104281
ecp_productSecret: OTRlNjNiNTE0OGFiMDEwMmM2ZmU=
draft_property_id: 11314
identifier_name: identifier_142c5
property_id: 11604
category_id: 28
ecp_deviceId: 10082954
ecp_deviceSecret: NTE1MDk1MDkxODAyMDQxZTA4Yjc=
batch_id: 100441
channel_id: 223
group_id: 373
destination_id: 14262
edge_router_id: 11423
router_id: 11424
rule_id: 8ae48e9673e145580173e6aba81f000f
ecp_node_deviceId: 10082957
ecp_node_deviceSecret: MTg3OWI1NjkxM2UwM2I1M2IwNjI=
ecp_productId: 104282
ecp_productSecret: YTAzMDYyYTMxMTlkODNiYjlhZWY=
draft_property_id: 11318
identifier_name: identifier_1da3e
property_id: 11615
category_id: 28
ecp_deviceId: 10082958
ecp_deviceSecret: ZGRkYjM3MzUzZGEyYTczM2IyZjA=
batch_id: 100442
channel_id: 224
group_id: 374
destination_id: 14263
edge_router_id: 11425
router_id: 11426
rule_id: 8ae48e9673e145580173e6cf788b0011
ecp_node_deviceId: 10082961
ecp_node_deviceSecret: NTMyNzcwMzEzN2QzYzY5ZWQyMGY=
ecp_productId: 104283
ecp_productSecret: MDliNjk4NmU5MTE4OTAyZWQ5YmM=
draft_property_id: 11319
identifier_name: identifier_c5f24
property_id: 11616
category_id: 28
ecp_deviceId: 10082962
ecp_deviceSecret: MTUwNmJlZTkyNzEyZmVmYWM2NzE=
batch_id: 100443
channel_id: 225
group_id: 375
destination_id: 14264
edge_router_id: 11427
router_id: 11428
rule_id: 8ae48e9673e145580173e6d820080013
ecp_node_deviceId: 10082965
ecp_node_deviceSecret: MDg2ODExYTYyZDE2MzEwNzJlYmQ=
ecp_node_deviceId: 10082966
ecp_node_deviceSecret: YWU3ZGE1MDljN2YwOTY4OTlkY2Q=
ecp_node_deviceId: 10082967
ecp_node_deviceSecret: NzAzMGRjZWE0MDZlMGU0N2EzNDU=
ecp_productId: 104284
ecp_productSecret: NjQ2YTg4MWE1NDVjM2RlODZlMzc=
draft_property_id: 11320
identifier_name: identifier_35db4
property_id: 11617
category_id: 28
ecp_deviceId: 10082968
ecp_deviceSecret: NjcxZDQ4M2Q1YzZmNmFmNzlmNWU=
batch_id: 100444
channel_id: 226
group_id: 376
destination_id: 14265
edge_router_id: 11429
router_id: 11430
rule_id: 8ae48e9673e145580173e70fdb1e0015
ecp_node_deviceId: 10082971
ecp_node_deviceSecret: M2FmNDQzNWJlOWNjNTJkMTE3NWU=
ecp_productId: 104285
ecp_productSecret: ZTk4YjBmNDk2Y2VmYmJmMzBjZjA=
draft_property_id: 11321
identifier_name: identifier_4503c
property_id: 11618
category_id: 28
ecp_deviceId: 10082972
ecp_deviceSecret: NTZlOTA2OGZiNTRkZDczMjBhZjI=
batch_id: 100445
channel_id: 227
group_id: 377
destination_id: 14266
edge_router_id: 11431
router_id: 11432
rule_id: 8ae48e9673e145580173e71095170017
