dmp_productId: 104333
dmp_productSecret: N2UyYjUxYWJjMDZjOWQzODlmOWE=
dmp_productId: 104334
dmp_productSecret: ZjJhODAxOGM1ODk1NTlkODgyZjQ=
draft_id: 0
draft_property_id: 11384
identifier_name: identifier_dae13
property_id: 11759
category_id: 28
dmp_deviceId: 10087762
dmp_deviceSecret: ZDNjMGQ1ZjkxOGI4MGE5MzlkYmI=
batch_id: 100541
group_id: 401
script_id: 456
mail_id: 8ae48e9673e1455801740b1d3800004d
template_id: 8ae48e9673e1455801740b1d392a004e
dmp_productId: 100152
dmp_productSecret: ZGJiNmFlNTBmNDVkNDhkNjdmMDI=
draft_id: 0
dmp_productId: 100153
dmp_productSecret: MDNjZDE3MTZkOTJiZmU5Mzk4YTQ=
draft_id: 0
draft_property_id: 11468
identifier_name: identifier_da15e
property_id: 11708
category_id: 100395
dmp_deviceId: 10002474
dmp_deviceSecret: MDk1MjQwNWYyODVmZTUxMTA0ODg=
batch_id: 100036
group_id: 377
script_id: 467
destination_id: 35
router_id: 41
rule_id: 8a7e9e067400be8901740b22ae1e000d
mail_id: 8a7e9e067400be8901740b22b6d7000e
template_id: 8a7e9e067400be8901740b22bc96000f
ecp_node_deviceId: 10002477
ecp_node_deviceSecret: ZjA4NjQxNjhjMTU5NDhkMmRiNjE=
ecp_node_deviceId: 10002478
ecp_node_deviceSecret: NjkyNWU0NmU3MWIyOGRlZTg2M2Q=
ecp_productId: 100155
ecp_productSecret: OTg4Zjk0NDdlZmU5MjFhMTU2Zjk=
draft_property_id: 11469
identifier_name: identifier_b3ced
property_id: 11709
category_id: 100395
ecp_deviceId: 10002479
ecp_deviceSecret: YmE2MzgxY2Q4YTgyNTA5NGRhZDg=
batch_id: 100037
channel_id: 202
group_id: 378
destination_id: 36
edge_router_id: 42
router_id: 43
rule_id: 8a7ebcff7400bf2401740b287417000d
ecp_productId: 100157
ecp_productSecret: MmZjMDI2YmJkNTM4NjRiZDFkMjM=
draft_property_id: 11470
identifier_name: identifier_d15fe
property_id: 11710
dmp_productId: 100158
dmp_productSecret: MzdkNWFhYzY4YzhkNjIwYTg2ZmU=
draft_id: 0
draft_property_id: 11471
identifier_name: identifier_5cba2
property_id: 11711
category_id: 100395
dmp_deviceId: 10002482
dmp_deviceSecret: NTM0MmY5Y2YyMTY4MmVjZDVlZTE=
batch_id: 100038
group_id: 379
script_id: 468
destination_id: 37
router_id: 44
rule_id: 8a7ebcff7400bf2401740b43a8e3000f
mail_id: 8a7ebcff7400bf2401740b43b1ac0010
template_id: 8a7ebcff7400bf2401740b43b4ce0011
dmp_productId: 100159
dmp_productSecret: YTExMjUwMjU2MTlhZTBmMWU5ZmU=
draft_id: 0
draft_property_id: 11472
identifier_name: identifier_dca42
property_id: 11712
category_id: 100395
dmp_deviceId: 10002485
dmp_deviceSecret: ZTI0YThhNWY1MDVhMzc1N2I0NzQ=
batch_id: 100039
group_id: 380
script_id: 469
destination_id: 38
router_id: 45
rule_id: 8a7e9e067400be8901740b492e2d0011
mail_id: 8a7e9e067400be8901740b49369e0012
template_id: 8a7e9e067400be8901740b4939b90013
ecp_node_deviceId: 10002488
ecp_node_deviceSecret: ODg1Y2MzY2QwMGRkNDQ5MDQwN2I=
ecp_productId: 100160
ecp_productSecret: YmFiZWQ0OGY0MTE3ZjYxMjA4NWM=
draft_property_id: 11473
identifier_name: identifier_15edf
property_id: 11713
category_id: 100395
ecp_deviceId: 10002489
ecp_deviceSecret: NzQyOWFmY2QyOWEwMzM4N2NhZGQ=
batch_id: 100040
channel_id: 203
group_id: 381
destination_id: 39
edge_router_id: 46
router_id: 47
rule_id: 8a7e9e067400be8901740e9471400014
