dmp_productId: 100568
dmp_productSecret: ZmVhOGU1YTA1MzcxZTNiZTdhYzU=
dmp_productId_lwm2m: 100569
dmp_productSecret_lwm2m: MjM0M2Y4NDc5NjY4YWMzNjVlYjk=
dmp_productId_tcp: 100570
dmp_productSecret_tcp: ZjUzMDhiNjRlN2Y2MTc3NDAwY2M=
dmp_productId_modbus: 100571
dmp_productSecret_modbus: NDc3NmUwNzQzOWY4NWU1ODMxYzQ=
dmp_productId_http: 100572
dmp_productSecret_http: YmQ4YjZhMmRiNjMzNzZlNjkyNDY=
draft_id: 0
draft_property_id: 3236
identifier_name: identifier_cdb24
property_id: 12489
category_id: 1516
dmp_deviceId: 10005412
dmp_deviceSecret: MjI2YzY2MTRiMGVhMzFmYTQwZjg=
batch_id: 100180
group_id: 412
script_id: 466
destination_id: 14215
router_id: 11354
rule_id: 8a7e936b74d2752b01752f74e0430002
mail_id: 8a7e936b74d2752b01752f74e89a0003
template_id: 8a7e9c1874d2754101752f7500370007
